### ISSUE TITLE
Possible with React Native? 

### ISSUE THREAD

**Issue by julioom** [bagongkia/react-image-picker#2]
Hello 
I'm developing a React Native project and I saw your component and it looks very interesting. 
Is it possible to use with React Native? 

Thanks ;)

**Comment by bagongkia** [comment]
Hello,
I think you won't use it at React Native...So far that what I have known, React Native and React's components are different things..


Get organized with Yahoo Mail 
 
  On Fri, Mar 9, 2018 at 8:34 PM, julioom<notifications@github.com> wrote:   
Hello
I'm developing a React Native project and I saw your component and it looks very interesting.
Is it possible to use with React Native?

Thanks ;)
